// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"fmt"
	"path/filepath"
)

// GameData 汇总各表数据；请使用与 excel2json 配置的 jsonPath 目录调用 LoadGameData（扩展名为 .bin（紧凑表二进制），与生成时 binaryExport 一致）。
type GameData struct {
	TBTestTable
}

// LoadGameData 在 dataDir 下加载全部表文件（扩展名由生成时 binaryExport 决定：.bin（紧凑表二进制））。
func LoadGameData(dataDir string) (*GameData, error) {
	d := &GameData{}
	if err := d.TBTestTable.load(filepath.Join(dataDir, "TBTest.bin")); err != nil {
		return nil, fmt.Errorf("load TBTest.bin: %w", err)
	}
	return d, nil
}
