// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"ctc/pkg/tablebin"
	"encoding/json"
)

// StructTest 由策划表 @Type 生成。
type StructTest struct {
	iD  int // ID
	num int // 数量
}

type structJSONAux_StructTest struct {
	ID  int `json:"ID"`  // ID
	Num int `json:"Num"` // 数量
}

func (s *StructTest) UnmarshalJSON(data []byte) error {
	var u structJSONAux_StructTest
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	s.iD = u.ID
	s.num = u.Num
	return nil
}

func (s *StructTest) deserialize(dec *tablebin.Decoder) (err error) {
	s.iD, err = dec.ReadInt()
	if err != nil {
		return err
	}
	s.num, err = dec.ReadInt()
	if err != nil {
		return err
	}
	return nil
}

func (s *StructTest) GetID() int {
	return s.iD
}

func (s *StructTest) GetNum() int {
	return s.num
}
