// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"encoding/json"
	"os"
	"slices"
)

// TBTest_rowGrp_group1 表 "TBTest" 分组 "group1"（由行扁平字段组装的视图，JSON 中无此嵌套）。
type TBTest_rowGrp_group1 struct {
	field1 int64  // 字段名1
	field2 string // 字段名2
}

func (g *TBTest_rowGrp_group1) GetField1() int64 {
	return g.field1
}

func (g *TBTest_rowGrp_group1) GetField2() string {
	return g.field2
}

// TBTest_rowIdx_idx1 表 "TBTest" 索引 "idx1"（由行扁平字段组装的视图，JSON 中无此嵌套）。
type TBTest_rowIdx_idx1 struct {
	field3 float64 // 字段名3
	field4 int     // 字段名4
}

func (g *TBTest_rowIdx_idx1) GetField3() float64 {
	return g.field3
}

func (g *TBTest_rowIdx_idx1) GetField4() int {
	return g.field4
}

// TBTestRow 对应表 "TBTest" 的一行（JSON 扁平；@Type「分组/索引」用于行视图与 Table 查询）。
type TBTestRow struct {
	id      int64
	field1  int64        // 字段名1
	field2  string       // 字段名2
	field3  float64      // 字段名3
	field4  int          // 字段名4
	field5  []int64      // 字段名5
	field6  []string     // 字段名6
	field7  []float64    // 字段名7
	field8  []int        // 字段名8
	field9  EnumTest     // 字段名9
	field10 []EnumTest   // 字段名10
	field11 StructTest   // 字段名11
	field12 []StructTest // 字段名12
}

type rowJSONAux_TBTest struct {
	ID      int64        `json:"id"`
	Field1  int64        `json:"Field1"`  // 字段名1
	Field2  string       `json:"Field2"`  // 字段名2
	Field3  float64      `json:"Field3"`  // 字段名3
	Field4  int          `json:"Field4"`  // 字段名4
	Field5  []int64      `json:"Field5"`  // 字段名5
	Field6  []string     `json:"Field6"`  // 字段名6
	Field7  []float64    `json:"Field7"`  // 字段名7
	Field8  []int        `json:"Field8"`  // 字段名8
	Field9  EnumTest     `json:"Field9"`  // 字段名9
	Field10 []EnumTest   `json:"Field10"` // 字段名10
	Field11 StructTest   `json:"Field11"` // 字段名11
	Field12 []StructTest `json:"Field12"` // 字段名12
}

func (r *TBTestRow) UnmarshalJSON(data []byte) error {
	var u rowJSONAux_TBTest
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	r.id = u.ID
	r.field1 = u.Field1
	r.field2 = u.Field2
	r.field3 = u.Field3
	r.field4 = u.Field4
	r.field5 = u.Field5
	r.field6 = u.Field6
	r.field7 = u.Field7
	r.field8 = u.Field8
	r.field9 = u.Field9
	r.field10 = u.Field10
	r.field11 = u.Field11
	r.field12 = u.Field12
	return nil
}

func (r *TBTestRow) GetID() int64 {
	return r.id
}

func (r *TBTestRow) GetField1() int64 {
	return r.field1
}

func (r *TBTestRow) GetField2() string {
	return r.field2
}

func (r *TBTestRow) GetField3() float64 {
	return r.field3
}

func (r *TBTestRow) GetField4() int {
	return r.field4
}

func (r *TBTestRow) GetField5() []int64 {
	return slices.Clone(r.field5)
}

func (r *TBTestRow) GetField6() []string {
	return slices.Clone(r.field6)
}

func (r *TBTestRow) GetField7() []float64 {
	return slices.Clone(r.field7)
}

func (r *TBTestRow) GetField8() []int {
	return slices.Clone(r.field8)
}

func (r *TBTestRow) GetField9() EnumTest {
	return r.field9
}

func (r *TBTestRow) GetField10() []EnumTest {
	return slices.Clone(r.field10)
}

func (r *TBTestRow) GetField11() StructTest {
	return r.field11
}

func (r *TBTestRow) GetField12() []StructTest {
	return slices.Clone(r.field12)
}

func (r *TBTestRow) ViewAsGroup1() TBTest_rowGrp_group1 {
	return TBTest_rowGrp_group1{
		field1: r.field1,
		field2: r.field2,
	}
}

func (r *TBTestRow) ViewAsIndex() TBTest_rowIdx_idx1 {
	return TBTest_rowIdx_idx1{
		field3: r.field3,
		field4: r.field4,
	}
}

// TBTest_group1 构造 @Type 分组 "group1" 的 map 键（形参与组内字段顺序、类型一致）。
func TBTest_group1(field1 int64, field2 string) TBTest_rowGrp_group1 {
	return TBTest_rowGrp_group1{
		field1: field1, // 字段名1
		field2: field2, // 字段名2
	}
}

// TBTest_idx1 构造 @Type 索引 "idx1" 的 map 键（形参与组内字段顺序、类型一致）。
func TBTest_idx1(field3 float64, field4 int) TBTest_rowIdx_idx1 {
	return TBTest_rowIdx_idx1{
		field3: field3, // 字段名3
		field4: field4, // 字段名4
	}
}

type TBTestTable struct {
	dict           map[int64]*TBTestRow
	list           []*TBTestRow
	byGroup_group1 map[TBTest_rowGrp_group1][]*TBTestRow // @Type 分组 "group1"
	byIndex_idx1   map[TBTest_rowIdx_idx1]*TBTestRow     // @Type 索引 "idx1"（复合键唯一）
}

func (r *TBTestTable) load(path string) error {
	var err error
	r.list, err = r.deserialize(path)
	if err != nil {
		return err
	}
	r.dict = make(map[int64]*TBTestRow)
	for _, row := range r.list {
		r.dict[row.GetID()] = row
	}
	r.initGroupAndIndex()
	return nil
}

func (r *TBTestTable) deserialize(path string) ([]*TBTestRow, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var list []*TBTestRow
	if err := json.Unmarshal(data, &list); err != nil {
		return nil, err
	}
	return list, nil
}

func (r *TBTestTable) initGroupAndIndex() {
	r.byGroup_group1 = make(map[TBTest_rowGrp_group1][]*TBTestRow)
	r.byIndex_idx1 = make(map[TBTest_rowIdx_idx1]*TBTestRow)
	for _, row := range r.list {
		kg0 := TBTest_group1(row.field1, row.field2)
		r.byGroup_group1[kg0] = append(r.byGroup_group1[kg0], row)
		ik0 := TBTest_idx1(row.field3, row.field4)
		r.byIndex_idx1[ik0] = row
	}
}

// GetRowsByGroupKey 按 @Type 分组键查询行（形参顺序、类型与 TBTest_group1 一致）。
func (r *TBTestTable) GetRowsByGroupKey(field1 int64, field2 string) []*TBTestRow {
	k := TBTest_group1(field1, field2)
	return r.byGroup_group1[k]
}

// GetByIndexKey 按 @Type 索引查询单行（形参顺序、类型与 TBTest_idx1 一致；复合键表内唯一）。
func (r *TBTestTable) GetByIndexKey(field3 float64, field4 int) *TBTestRow {
	k := TBTest_idx1(field3, field4)
	return r.byIndex_idx1[k]
}

func (r *TBTestTable) Get(id int64) *TBTestRow {
	row, _ := r.dict[id]
	return row
}

func (r *TBTestTable) Index(idx int) *TBTestRow {
	if idx < 0 || idx >= len(r.list) {
		return nil
	}
	return r.list[idx]
}

func (r *TBTestTable) Range(f func(*TBTestRow) bool) {
	for _, row := range r.dict {
		if !f(row) {
			return
		}
	}
}

func (r *TBTestTable) SeqRange(f func(*TBTestRow) bool) {
	for _, row := range r.list {
		if !f(row) {
			return
		}
	}
}

func (r *TBTestTable) Len() int {
	return len(r.dict)
}
