package gogen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"ctc/internal/excelconv"
)

// WritePackage 根据 Schema 写出可编译的 Go 包：枚举、嵌套结构（小写字段+Getter+UnmarshalJSON）、表行及 Load。
func WritePackage(dir, pkg string, schema *excelconv.Schema, target excelconv.ExportTarget) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if pkg == "" {
		pkg = "gamedata"
	}

	var files []fileOut

	// 枚举
	var enames []string
	for n := range schema.Enums {
		enames = append(enames, n)
	}
	sort.Strings(enames)
	if len(enames) > 0 {
		b := new(strings.Builder)
		writeHeaderTypesOnly(b, pkg)
		for _, en := range enames {
			members := schema.Enums[en]
			fmt.Fprintf(b, "\n// %s 由策划表 @Type 生成。\ntype %s int\n\nconst (\n", en, en)
			for _, m := range members {
				cname := constName(en, m.Name)
				v := 0
				if schema.EnumValue[en] != nil {
					v = schema.EnumValue[en][m.Name]
				}
				fmt.Fprintf(b, "\t%s %s = %d // %s\n", cname, en, v, m.NameCN)
			}
			fmt.Fprintf(b, ")\n")
		}
		files = append(files, fileOut{"enums_gen.go", b.String()})
	}

	// 策划「结构」
	var snames []string
	for n := range schema.Structs {
		snames = append(snames, n)
	}
	sort.Strings(snames)
	if len(snames) > 0 {
		structNeedSlices := false
		for _, sn := range snames {
			if structFieldsNeedSlices(visibleStructFields(schema.Structs[sn], target)) {
				structNeedSlices = true
				break
			}
		}
		b := new(strings.Builder)
		writeStructFileHeader(b, pkg, structNeedSlices)
		for _, sn := range snames {
			writeConfigStruct(b, sn, visibleStructFields(schema.Structs[sn], target), schema)
		}
		files = append(files, fileOut{"structs_gen.go", b.String()})
	}

	tkeys := sortedTableKeys(schema.Tables)
	if len(tkeys) > 0 {
		b := new(strings.Builder)
		needSlices := false
		for _, tname := range tkeys {
			visible := visibleTableFields(schema.Tables[tname], target)
			if tableFieldsNeedSlices(visible) {
				needSlices = true
			}
		}
		writeTableFileHeader(b, pkg, needSlices)
		for _, tname := range tkeys {
			visible := visibleTableFields(schema.Tables[tname], target)
			writeTableRowStruct(b, tname, visible, schema)
			writeTableContainer(b, tname, schema)
		}
		files = append(files, fileOut{"tables_gen.go", b.String()})
	}

	for _, fo := range files {
		src, err := format.Source([]byte(fo.content))
		if err != nil {
			return fmt.Errorf("format %s: %w\n%s", fo.name, err, fo.content)
		}
		path := filepath.Join(dir, fo.name)
		if err := os.WriteFile(path, src, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func visibleTableFields(fields []excelconv.Field, target excelconv.ExportTarget) []excelconv.Field {
	var v []excelconv.Field
	for _, fld := range fields {
		if !excelconv.FieldVisible(fld.Filter, target) {
			continue
		}
		if strings.EqualFold(fld.Name, excelconv.RowJSONIDKey) {
			continue
		}
		v = append(v, fld)
	}
	return v
}

func visibleStructFields(fields []excelconv.StructField, target excelconv.ExportTarget) []excelconv.StructField {
	var v []excelconv.StructField
	for _, sf := range fields {
		if !excelconv.FieldVisible(sf.Filter, target) {
			continue
		}
		v = append(v, sf)
	}
	return v
}

func tableFieldsNeedSlices(fields []excelconv.Field) bool {
	for _, f := range fields {
		if f.ArraySplit != "" {
			return true
		}
	}
	return false
}

func structFieldsNeedSlices(fields []excelconv.StructField) bool {
	for _, f := range fields {
		if f.ArraySplit != "" {
			return true
		}
	}
	return false
}

func writeStructFileHeader(b *strings.Builder, pkg string, withSlices bool) {
	fmt.Fprintf(b, `// Code generated by excel2json from @Type. DO NOT EDIT.

package %s

import (
	"encoding/json"
`, pkg)
	if withSlices {
		fmt.Fprintf(b, "\t\"slices\"\n")
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeTableFileHeader(b *strings.Builder, pkg string, withSlices bool) {
	fmt.Fprintf(b, `// Code generated by excel2json from @Type. DO NOT EDIT.

package %s

import (
	"encoding/json"
	"os"
`, pkg)
	if withSlices {
		fmt.Fprintf(b, "\t\"slices\"\n")
	}
	fmt.Fprintf(b, ")\n\n")
}

func writeConfigStruct(b *strings.Builder, sn string, visible []excelconv.StructField, schema *excelconv.Schema) {
	fmt.Fprintf(b, "\n// %s 由策划表 @Type 生成。\ntype %s struct {\n", sn, sn)
	for _, sf := range visible {
		priv := privateFieldIdent(sf.Name)
		got := goFieldTypeStruct(sf, schema)
		fmt.Fprintf(b, "\t%s %s\n", priv, got)
	}
	fmt.Fprintf(b, "}\n")

	aux := structJSONAuxTypeName(sn)
	fmt.Fprintf(b, "\ntype %s struct {\n", aux)
	for _, sf := range visible {
		got := goFieldTypeStruct(sf, schema)
		ex := exportedGoIdent(sf.Name)
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", ex, got, sf.Name)
	}
	fmt.Fprintf(b, "}\n")

	fmt.Fprintf(b, "\nfunc (s *%s) UnmarshalJSON(data []byte) error {\n\tvar u %s\n\tif err := json.Unmarshal(data, &u); err != nil {\n\t\treturn err\n\t}\n", sn, aux)
	for _, sf := range visible {
		priv := privateFieldIdent(sf.Name)
		ex := exportedGoIdent(sf.Name)
		fmt.Fprintf(b, "\ts.%s = u.%s\n", priv, ex)
	}
	fmt.Fprintf(b, "\treturn nil\n}\n")

	for _, sf := range visible {
		priv := privateFieldIdent(sf.Name)
		got := goFieldTypeStruct(sf, schema)
		gtr := getterMethodName(sf.Name)
		if strings.HasPrefix(got, "[]") {
			fmt.Fprintf(b, "\nfunc (s *%s) %s() %s {\n\treturn slices.Clone(s.%s)\n}\n", sn, gtr, got, priv)
		} else {
			fmt.Fprintf(b, "\nfunc (s *%s) %s() %s {\n\treturn s.%s\n}\n", sn, gtr, got, priv)
		}
	}
}

func tableRowPrimaryKeyGoType(schema *excelconv.Schema, table string) string {
	switch schema.PrimaryKeyTypeForTable(table) {
	case "int":
		return "int"
	case "string":
		return "string"
	default:
		return "int64"
	}
}

func writeTableRowStruct(b *strings.Builder, tname string, visible []excelconv.Field, schema *excelconv.Schema) {
	idGo := tableRowPrimaryKeyGoType(schema, tname)
	fmt.Fprintf(b, "\n// %sRow 对应表 %q 的一行（首列为唯一 id，类型见 @Type「主键」）。\ntype %sRow struct {\n", tname, tname, tname)
	fmt.Fprintf(b, "\tid %s\n", idGo)
	for _, fld := range visible {
		priv := privateFieldIdent(fld.Name)
		got := goFieldTypeTable(fld, schema)
		fmt.Fprintf(b, "\t%s %s\n", priv, got)
	}
	fmt.Fprintf(b, "}\n")

	aux := rowJSONAuxTypeName(tname)
	fmt.Fprintf(b, "\ntype %s struct {\n", aux)
	fmt.Fprintf(b, "\tID %s `json:\"%s\"`\n", idGo, excelconv.RowJSONIDKey)
	for _, fld := range visible {
		got := goFieldTypeTable(fld, schema)
		ex := exportedGoIdent(fld.Name)
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", ex, got, fld.Name)
	}
	fmt.Fprintf(b, "}\n")

	fmt.Fprintf(b, "\nfunc (r *%sRow) UnmarshalJSON(data []byte) error {\n\tvar u %s\n\tif err := json.Unmarshal(data, &u); err != nil {\n\t\treturn err\n\t}\n", tname, aux)
	fmt.Fprintf(b, "\tr.id = u.ID\n")
	for _, fld := range visible {
		priv := privateFieldIdent(fld.Name)
		ex := exportedGoIdent(fld.Name)
		fmt.Fprintf(b, "\tr.%s = u.%s\n", priv, ex)
	}
	fmt.Fprintf(b, "\treturn nil\n}\n")

	fmt.Fprintf(b, "\nfunc (r *%sRow) GetID() %s {\n\treturn r.id\n}\n", tname, idGo)
	for _, fld := range visible {
		priv := privateFieldIdent(fld.Name)
		got := goFieldTypeTable(fld, schema)
		gtr := getterMethodName(fld.Name)
		if strings.HasPrefix(got, "[]") {
			fmt.Fprintf(b, "\nfunc (r *%sRow) %s() %s {\n\treturn slices.Clone(r.%s)\n}\n", tname, gtr, got, priv)
		} else {
			fmt.Fprintf(b, "\nfunc (r *%sRow) %s() %s {\n\treturn r.%s\n}\n", tname, gtr, got, priv)
		}
	}
}

func writeTableContainer(b *strings.Builder, tname string, schema *excelconv.Schema) {
	idGo := tableRowPrimaryKeyGoType(schema, tname)
	fmt.Fprintf(b, "\n\ntype %sTable struct {\n", tname)
	fmt.Fprintf(b, "\tdict map[%s]*%sRow\n", idGo, tname)
	fmt.Fprintf(b, "\tlist []*%sRow\n", tname)
	fmt.Fprintf(b, "}\n")

	fmt.Fprintf(b, `
func (r *%sTable) load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &r.list); err != nil {
		return err
	}
	r.dict = make(map[%s]*%sRow)
	for _, row := range r.list {
		r.dict[row.GetID()] = row
	}
	return nil
}

func (r *%sTable) Get(id %s) *%sRow {
	row, _ := r.dict[id]
	return row
}

func (r *%sTable) Index(idx int) *%sRow {
	if idx < 0 || idx >= len(r.list) {
		return nil
	}
	return r.list[idx]
}

func (r *%sTable) Range(f func(*%sRow) bool) {
	for _, row := range r.dict {
		if !f(row) {
			return
		}
	}
}

func (r *%sTable) SeqRange(f func(*%sRow) bool) {
	for _, row := range r.list {
		if !f(row) {
			return
		}
	}
}

func (r *%sTable) Len() int {
	return len(r.dict)
}
`, tname, idGo, tname, tname, idGo, tname, tname, tname, tname, tname, tname, tname, tname)
}

// GenerateBundle 写出 GameData 与 LoadGameData（jsonDir 应与 excel2json -out 一致）。
func GenerateBundle(dir, pkg string, schema *excelconv.Schema, _ excelconv.ExportTarget) error {
	var tnames []string
	for n := range schema.Tables {
		tnames = append(tnames, n)
	}
	if len(tnames) == 0 {
		_ = os.Remove(filepath.Join(dir, "loader_gen.go"))
		return nil
	}
	sort.Strings(tnames)

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by excel2json from @Type. DO NOT EDIT.

package %s

import (
	"fmt"
	"path/filepath"
)

// GameData 汇总各表数据；请使用与 excel2json -out 相同的目录调用 LoadGameData。
type GameData struct {
`, pkg)
	if len(tnames) == 1 {
		fmt.Fprintf(&buf, "\t%sTable\n", tnames[0])
	} else {
		for _, t := range tnames {
			fname := gameDataFieldName(t)
			fmt.Fprintf(&buf, "\t%s %sTable\n", fname, t)
		}
	}
	fmt.Fprintf(&buf, `}

// LoadGameData 在 jsonDir 下按 «表名».json 加载全部表（JSON 为行对象数组）。
func LoadGameData(jsonDir string) (*GameData, error) {
	d := &GameData{}
`)
	if len(tnames) == 1 {
		t := tnames[0]
		j := t + ".json"
		fmt.Fprintf(&buf, "\tif err := d.%sTable.load(filepath.Join(jsonDir, %q)); err != nil {\n", t, j)
		fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"load %s: %%w\", err)\n", j)
		fmt.Fprintf(&buf, "\t}\n")
	} else {
		for _, t := range tnames {
			fname := gameDataFieldName(t)
			j := t + ".json"
			fmt.Fprintf(&buf, "\tif err := d.%s.load(filepath.Join(jsonDir, %q)); err != nil {\n", fname, j)
			fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"load %s: %%w\", err)\n", j)
			fmt.Fprintf(&buf, "\t}\n")
		}
	}
	fmt.Fprintf(&buf, "\treturn d, nil\n}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format loader_gen.go: %w", err)
	}
	return os.WriteFile(filepath.Join(dir, "loader_gen.go"), src, 0o644)
}

type fileOut struct {
	name    string
	content string
}

func writeHeaderTypesOnly(b *strings.Builder, pkg string) {
	fmt.Fprintf(b, `// Code generated by excel2json from @Type. DO NOT EDIT.

package %s

`, pkg)
}

func sortedTableKeys(m map[string][]excelconv.Field) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func goFieldTypeTable(f excelconv.Field, schema *excelconv.Schema) string {
	base := baseGoType(f.Type, schema)
	if f.ArraySplit != "" {
		return "[]" + base
	}
	return base
}

func goFieldTypeStruct(sf excelconv.StructField, schema *excelconv.Schema) string {
	base := baseGoType(sf.Type, schema)
	if sf.ArraySplit != "" {
		return "[]" + base
	}
	return base
}

func baseGoType(typeName string, schema *excelconv.Schema) string {
	switch typeName {
	case "string":
		return "string"
	case "int":
		return "int"
	case "int64":
		return "int64"
	default:
		if schema.Structs[typeName] != nil {
			return typeName
		}
		if schema.Enums[typeName] != nil {
			return typeName
		}
		return "string"
	}
}
