// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace GameData;

public partial class StructTest
{
	[JsonPropertyName("ID")] public int ID { get; set; } = default!;
	[JsonPropertyName("Num")] public int Num { get; set; } = default!;
}


