// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GameData;



public partial class EmojiRow
{
	[JsonPropertyName("id")] public long Id { get; set; }
	[JsonPropertyName("Name")] public string Name { get; set; } = default!;
	[JsonPropertyName("ShortName")] public string ShortName { get; set; } = default!;
	[JsonPropertyName("Icon")] public string Icon { get; set; } = default!;
	[JsonPropertyName("UnlockType")] public int UnlockType { get; set; } = default!;
	[JsonPropertyName("ConditionText")] public string ConditionText { get; set; } = default!;
	[JsonPropertyName("Speed")] public double[] Speed { get; set; } = default!;
	[JsonPropertyName("Grids")] public int Grids { get; set; } = default!;

	internal void ReadFrom(TableBinDecoder dec)
	{
		Id = dec.ReadInt64Zigzag();
		this.Name = dec.ReadString();
		this.ShortName = dec.ReadString();
		this.Icon = dec.ReadString();
		this.UnlockType = dec.ReadInt();
		this.ConditionText = dec.ReadString();
		this.Speed = dec.ReadFloat64Slice();
		this.Grids = dec.ReadInt();
	}
}

public partial class EmojiTable
{
	public List<EmojiRow> List { get; private set; } = new();
	public Dictionary<long, EmojiRow> Dict { get; private set; } = new();

	public void Load(string path)
	{
		var dec = TableBinDecoder.Open(path);
		var rows = new List<EmojiRow>();
		for (ulong i = 0; i < dec.NumRows; i++) {
			var row = new EmojiRow();
			row.ReadFrom(dec);
			rows.Add(row);
		}
		LoadFromRows(rows);
	}

	void LoadFromRows(List<EmojiRow> rows)
	{
		List = rows;
		Dict = new Dictionary<long, EmojiRow>();
		foreach (var row in rows) Dict[row.Id] = row;
		InitGroupAndIndex();
	}

	void InitGroupAndIndex()
	{
		foreach (var row in List) {
		}
	}

	public EmojiRow? Get(long id) => Dict.TryGetValue(id, out var r) ? r : null;

	public EmojiRow? Index(int idx) => (uint)idx < (uint)List.Count ? List[idx] : null;

	public void Range(System.Func<EmojiRow, bool> f) {
		foreach (var kv in Dict) { if (!f(kv.Value)) return; }
	}

	public void SeqRange(System.Func<EmojiRow, bool> f) {
		foreach (var row in List) { if (!f(row)) return; }
	}

	public int Len => Dict.Count;
}
