// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GameData;

public readonly record struct WallpaperRowGrp_group(string Video1, int Time1);

public readonly record struct WallpaperRowGrp_group2(string Video2, int Time2);


public readonly record struct WallpaperRowIdx_index1(string Video1, int Time1);


public partial class WallpaperRow
{
	[JsonPropertyName("id")] public long Id { get; set; }
	[JsonPropertyName("Cover")] public string Cover { get; set; } = default!;
	[JsonPropertyName("Video1")] public string Video1 { get; set; } = default!;
	[JsonPropertyName("Time1")] public int Time1 { get; set; } = default!;
	[JsonPropertyName("Video2")] public string Video2 { get; set; } = default!;
	[JsonPropertyName("Time2")] public int Time2 { get; set; } = default!;
	[JsonPropertyName("Type")] public int Type { get; set; } = default!;
	[JsonPropertyName("Video3")] public string Video3 { get; set; } = default!;
	[JsonPropertyName("Time3")] public int Time3 { get; set; } = default!;
	[JsonPropertyName("ShowRewardList")] public ItemConfig[] ShowRewardList { get; set; } = default!;

	public WallpaperRowGrp_group ViewAsGroup() => new WallpaperRowGrp_group(Video1, Time1);

	public WallpaperRowGrp_group2 ViewAsGroup2() => new WallpaperRowGrp_group2(Video2, Time2);

	public WallpaperRowIdx_index1 ViewAsIndex() => new WallpaperRowIdx_index1(Video1, Time1);

	internal void ReadFrom(TableBinDecoder dec)
	{
		Id = dec.ReadInt64Zigzag();
		this.Cover = dec.ReadString();
		this.Video1 = dec.ReadString();
		this.Time1 = dec.ReadInt();
		this.Video2 = dec.ReadString();
		this.Time2 = dec.ReadInt();
		this.Type = dec.ReadInt();
		this.Video3 = dec.ReadString();
		this.Time3 = dec.ReadInt();
		{
			int _nl = dec.ReadSliceLen();
			ShowRewardList = new ItemConfig[_nl];
			for (int _si = 0; _si < _nl; _si++) {
				ShowRewardList[_si] = new ItemConfig();
				ShowRewardList[_si].ReadFrom(dec);
			}
		}
	}
}

public partial class WallpaperTable
{
	public List<WallpaperRow> List { get; private set; } = new();
	public Dictionary<long, WallpaperRow> Dict { get; private set; } = new();
	private Dictionary<WallpaperRowGrp_group, List<WallpaperRow>> _byGroup_group = new();
	private Dictionary<WallpaperRowGrp_group2, List<WallpaperRow>> _byGroup_group2 = new();
	private Dictionary<WallpaperRowIdx_index1, WallpaperRow> _byIndex_index1 = new();

	public static WallpaperRowGrp_group Wallpaper_group(string Video1, int Time1) => new WallpaperRowGrp_group(Video1, Time1);

	public static WallpaperRowGrp_group2 Wallpaper_group2(string Video2, int Time2) => new WallpaperRowGrp_group2(Video2, Time2);

	public static WallpaperRowIdx_index1 Wallpaper_index1(string Video1, int Time1) => new WallpaperRowIdx_index1(Video1, Time1);

	public void Load(string path)
	{
		var dec = TableBinDecoder.Open(path);
		var rows = new List<WallpaperRow>();
		for (ulong i = 0; i < dec.NumRows; i++) {
			var row = new WallpaperRow();
			row.ReadFrom(dec);
			rows.Add(row);
		}
		LoadFromRows(rows);
	}

	void LoadFromRows(List<WallpaperRow> rows)
	{
		List = rows;
		Dict = new Dictionary<long, WallpaperRow>();
		foreach (var row in rows) Dict[row.Id] = row;
		InitGroupAndIndex();
	}

	void InitGroupAndIndex()
	{
		_byGroup_group.Clear();
		_byGroup_group2.Clear();
		_byIndex_index1.Clear();
		foreach (var row in List) {
			var kg0 = Wallpaper_group(row.Video1, row.Time1);
			if (!_byGroup_group.TryGetValue(kg0, out var _lg0)) { _lg0 = new List<WallpaperRow>(); _byGroup_group[kg0] = _lg0; }
			_lg0.Add(row);

			var kg1 = Wallpaper_group2(row.Video2, row.Time2);
			if (!_byGroup_group2.TryGetValue(kg1, out var _lg1)) { _lg1 = new List<WallpaperRow>(); _byGroup_group2[kg1] = _lg1; }
			_lg1.Add(row);

			var ik0 = Wallpaper_index1(row.Video1, row.Time1);
			_byIndex_index1[ik0] = row;

		}
	}

	public IReadOnlyList<WallpaperRow> GetRowsByGroup_group(string Video1, int Time1) {
		var k = Wallpaper_group(Video1, Time1);
		return _byGroup_group.TryGetValue(k, out var v) ? v : System.Array.Empty<WallpaperRow>();
	}

	public IReadOnlyList<WallpaperRow> GetRowsByGroup_group2(string Video2, int Time2) {
		var k = Wallpaper_group2(Video2, Time2);
		return _byGroup_group2.TryGetValue(k, out var v) ? v : System.Array.Empty<WallpaperRow>();
	}

	public WallpaperRow? GetByIndexKey(string Video1, int Time1) {
		var k = Wallpaper_index1(Video1, Time1);
		return _byIndex_index1.TryGetValue(k, out var v) ? v : null;
	}

	public WallpaperRow? Get(long id) => Dict.TryGetValue(id, out var r) ? r : null;

	public WallpaperRow? Index(int idx) => (uint)idx < (uint)List.Count ? List[idx] : null;

	public void Range(System.Func<WallpaperRow, bool> f) {
		foreach (var kv in Dict) { if (!f(kv.Value)) return; }
	}

	public void SeqRange(System.Func<WallpaperRow, bool> f) {
		foreach (var row in List) { if (!f(row)) return; }
	}

	public int Len => Dict.Count;
}
