// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

// EnumTest 由策划表 @Type 生成。
type EnumTest int32

const (
	EnumTestEnum1 EnumTest = 1 // 枚举1
	EnumTestEnum2 EnumTest = 2 // 枚举2
	EnumTestEnum3 EnumTest = 3 // 枚举3
)

// EnumTest_name 数值 → @Type 成员名。
var EnumTest_name = map[int32]string{
	1: "enum1",
	2: "enum2",
	3: "enum3",
}

// EnumTest_value @Type 成员名 → 数值。
var EnumTest_value = map[string]int32{
	"enum1": 1,
	"enum2": 2,
	"enum3": 3,
}
