// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"fmt"
	"path/filepath"
)

// GameData 汇总各表数据；请使用与 excel2json -out 相同的目录调用 LoadGameData。
type GameData struct {
	WallpaperTable
}

// LoadGameData 在 jsonDir 下按 «表名».json 加载全部表。
func LoadGameData(jsonDir string) (*GameData, error) {
	d := &GameData{}

	if err:= d.WallpaperTable.load(filepath.Join(jsonDir, "Wallpaper.json")) ;err != nil {
		return nil, fmt.Errorf("load Wallpaper.json: %w", err)
	}

	return d, nil
}
