// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"fmt"
	"path/filepath"
)

// GameData 汇总各表数据；请使用与 excel2json 配置的 jsonPath 目录调用 LoadGameData（扩展名为 .json（JSON 行数组），与生成时 binaryExport 一致）。
type GameData struct {
	Emoji     EmojiTable
	Wallpaper WallpaperTable
}

// LoadGameData 在 dataDir 下加载全部表文件（扩展名由生成时 binaryExport 决定：.json（JSON 行数组））。
func LoadGameData(dataDir string) (*GameData, error) {
	d := &GameData{}
	if err := d.Emoji.load(filepath.Join(dataDir, "Emoji.json")); err != nil {
		return nil, fmt.Errorf("load Emoji.json: %w", err)
	}
	if err := d.Wallpaper.load(filepath.Join(dataDir, "Wallpaper.json")); err != nil {
		return nil, fmt.Errorf("load Wallpaper.json: %w", err)
	}
	return d, nil
}
