// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"ctc/pkg/tablebin"
	"encoding/json"
	"slices"
)

// ItemConfig 由策划表 @Type 生成。
type ItemConfig struct {
	iD  int
	num int
}

func (row *ItemConfig) deserialize(dec *tablebin.Decoder) (err error) {
	row.iD, err = dec.ReadInt()
	if err != nil {
		return
	}
	row.num, err = dec.ReadInt()
	if err != nil {
		return
	}
	return
}


type structJSONAux_ItemConfig struct {
	ID  int `json:"ID"`
	Num int `json:"Num"`
}

func (s *ItemConfig) UnmarshalJSON(data []byte) error {
	var u structJSONAux_ItemConfig
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	s.iD = u.ID
	s.num = u.Num
	return nil
}

func (s *ItemConfig) GetID() int {
	return s.iD
}

func (s *ItemConfig) GetNum() int {
	return s.num
}

// LevelItemConfig 由策划表 @Type 生成。
type LevelItemConfig struct {
	start  int
	end    int
	reward []int
}

type structJSONAux_LevelItemConfig struct {
	Start  int   `json:"Start"`
	End    int   `json:"End"`
	Reward []int `json:"Reward"`
}

func (s *LevelItemConfig) UnmarshalJSON(data []byte) error {
	var u structJSONAux_LevelItemConfig
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	s.start = u.Start
	s.end = u.End
	s.reward = u.Reward
	return nil
}

func (s *LevelItemConfig) GetStart() int {
	return s.start
}

func (s *LevelItemConfig) GetEnd() int {
	return s.end
}

func (s *LevelItemConfig) GetReward() []int {
	return slices.Clone(s.reward)
}
