// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"encoding/json"
)

// StructTest 由策划表 @Type 生成。
type StructTest struct {
	iD  int
	num int
}

type structJSONAux_StructTest struct {
	ID  int `json:"ID"`
	Num int `json:"Num"`
}

func (s *StructTest) UnmarshalJSON(data []byte) error {
	var u structJSONAux_StructTest
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	s.iD = u.ID
	s.num = u.Num
	return nil
}

func (s *StructTest) GetID() int {
	return s.iD
}

func (s *StructTest) GetNum() int {
	return s.num
}
