// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"encoding/json"
	"slices"
)

// LevelItemConfig 由策划表 @Type 生成。
type LevelItemConfig struct {
	start  int
	end    int
	reward []int
}

type structJSONAux_LevelItemConfig struct {
	Start  int   `json:"Start"`
	End    int   `json:"End"`
	Reward []int `json:"Reward"`
}

func (s *LevelItemConfig) UnmarshalJSON(data []byte) error {
	var u structJSONAux_LevelItemConfig
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	s.start = u.Start
	s.end = u.End
	s.reward = u.Reward
	return nil
}

func (s *LevelItemConfig) GetStart() int {
	return s.start
}

func (s *LevelItemConfig) GetEnd() int {
	return s.end
}

func (s *LevelItemConfig) GetReward() []int {
	return slices.Clone(s.reward)
}
