// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"encoding/json"
	"os"
)

// WallpaperRow 对应表 "Wallpaper" 的一行（首列为唯一 id，类型见 @Type「主键」）。
type WallpaperRow struct {
	id        int64
	cover     string
	video1    string
	time1     int
	video2    string
	time2     int
	typeField int
	video3    string
	time3     int
}

type rowJSONAux_Wallpaper struct {
	ID     int64  `json:"id"`
	Cover  string `json:"Cover"`
	Video1 string `json:"Video1"`
	Time1  int    `json:"Time1"`
	Video2 string `json:"Video2"`
	Time2  int    `json:"Time2"`
	Type   int    `json:"Type"`
	Video3 string `json:"Video3"`
	Time3  int    `json:"Time3"`
}

func (r *WallpaperRow) UnmarshalJSON(data []byte) error {
	var u rowJSONAux_Wallpaper
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	r.id = u.ID
	r.cover = u.Cover
	r.video1 = u.Video1
	r.time1 = u.Time1
	r.video2 = u.Video2
	r.time2 = u.Time2
	r.typeField = u.Type
	r.video3 = u.Video3
	r.time3 = u.Time3
	return nil
}

func (r *WallpaperRow) GetID() int64 {
	return r.id
}

func (r *WallpaperRow) GetCover() string {
	return r.cover
}

func (r *WallpaperRow) GetVideo1() string {
	return r.video1
}

func (r *WallpaperRow) GetTime1() int {
	return r.time1
}

func (r *WallpaperRow) GetVideo2() string {
	return r.video2
}

func (r *WallpaperRow) GetTime2() int {
	return r.time2
}

func (r *WallpaperRow) GetType() int {
	return r.typeField
}

func (r *WallpaperRow) GetVideo3() string {
	return r.video3
}

func (r *WallpaperRow) GetTime3() int {
	return r.time3
}

type WallpaperTable struct {
	dict map[int64]*WallpaperRow
	list []*WallpaperRow
}

func (r *WallpaperTable) load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &r.list); err != nil {
		return err
	}
	r.dict = make(map[int64]*WallpaperRow)
	for _, row := range r.list {
		r.dict[row.GetID()] = row
	}
	return nil
}

func (r *WallpaperTable) Get(id int64) *WallpaperRow {
	row, _ := r.dict[id]
	return row
}

func (r *WallpaperTable) Index(idx int) *WallpaperRow {
	if idx < 0 || idx >= len(r.list) {
		return nil
	}
	return r.list[idx]
}

func (r *WallpaperTable) Range(f func(*WallpaperRow) bool) {
	for _, row := range r.dict {
		if !f(row) {
			return
		}
	}
}

func (r *WallpaperTable) SeqRange(f func(*WallpaperRow) bool) {
	for _, row := range r.list {
		if !f(row) {
			return
		}
	}
}

func (r *WallpaperTable) Len() int {
	return len(r.dict)
}
