// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"encoding/json"
	"os"
)

// Wallpaper_rowGrp_group 表 "Wallpaper" 分组 "group"（由行扁平字段组装的视图，JSON 中无此嵌套）。
type Wallpaper_rowGrp_group struct {
	video1 string
	time1  int
}

func (g *Wallpaper_rowGrp_group) GetVideo1() string {
	return g.video1
}

func (g *Wallpaper_rowGrp_group) GetTime1() int {
	return g.time1
}

// Wallpaper_rowGrp_group2 表 "Wallpaper" 分组 "group2"（由行扁平字段组装的视图，JSON 中无此嵌套）。
type Wallpaper_rowGrp_group2 struct {
	video2 string
	time2  int
}

func (g *Wallpaper_rowGrp_group2) GetVideo2() string {
	return g.video2
}

func (g *Wallpaper_rowGrp_group2) GetTime2() int {
	return g.time2
}

// Wallpaper_rowIdx_index1 表 "Wallpaper" 索引 "index1"（由行扁平字段组装的视图，JSON 中无此嵌套）。
type Wallpaper_rowIdx_index1 struct {
	video1 string
	time1  int
}

func (g *Wallpaper_rowIdx_index1) GetVideo1() string {
	return g.video1
}

func (g *Wallpaper_rowIdx_index1) GetTime1() int {
	return g.time1
}

// WallpaperRow 对应表 "Wallpaper" 的一行（JSON 扁平；@Type「分组/索引」用于行视图与 Table 查询）。
type WallpaperRow struct {
	id        int64
	cover     string
	video1    string
	time1     int
	video2    string
	time2     int
	typeField int
	video3    string
	time3     int
}

type rowJSONAux_Wallpaper struct {
	ID     int64  `json:"id"`
	Cover  string `json:"Cover"`
	Video1 string `json:"Video1"`
	Time1  int    `json:"Time1"`
	Video2 string `json:"Video2"`
	Time2  int    `json:"Time2"`
	Type   int    `json:"Type"`
	Video3 string `json:"Video3"`
	Time3  int    `json:"Time3"`
}

func (r *WallpaperRow) UnmarshalJSON(data []byte) error {
	var u rowJSONAux_Wallpaper
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	r.id = u.ID
	r.cover = u.Cover
	r.video1 = u.Video1
	r.time1 = u.Time1
	r.video2 = u.Video2
	r.time2 = u.Time2
	r.typeField = u.Type
	r.video3 = u.Video3
	r.time3 = u.Time3
	return nil
}

func (r *WallpaperRow) GetID() int64 {
	return r.id
}

func (r *WallpaperRow) GetCover() string {
	return r.cover
}

func (r *WallpaperRow) GetVideo1() string {
	return r.video1
}

func (r *WallpaperRow) GetTime1() int {
	return r.time1
}

func (r *WallpaperRow) GetVideo2() string {
	return r.video2
}

func (r *WallpaperRow) GetTime2() int {
	return r.time2
}

func (r *WallpaperRow) GetType() int {
	return r.typeField
}

func (r *WallpaperRow) GetVideo3() string {
	return r.video3
}

func (r *WallpaperRow) GetTime3() int {
	return r.time3
}

func (r *WallpaperRow) ViewAsGroup() Wallpaper_rowGrp_group {
	return Wallpaper_rowGrp_group{
		video1: r.video1,
		time1:  r.time1,
	}
}

func (r *WallpaperRow) ViewAsGroup2() Wallpaper_rowGrp_group2 {
	return Wallpaper_rowGrp_group2{
		video2: r.video2,
		time2:  r.time2,
	}
}

func (r *WallpaperRow) ViewAsIndex() Wallpaper_rowIdx_index1 {
	return Wallpaper_rowIdx_index1{
		video1: r.video1,
		time1:  r.time1,
	}
}

// Wallpaper_group 构造 @Type 分组 "group" 的 map 键（形参与组内字段顺序、类型一致）。
func Wallpaper_group(video1 string, time1 int) Wallpaper_rowGrp_group {
	return Wallpaper_rowGrp_group{
		video1: video1,
		time1:  time1,
	}
}

// Wallpaper_group2 构造 @Type 分组 "group2" 的 map 键（形参与组内字段顺序、类型一致）。
func Wallpaper_group2(video2 string, time2 int) Wallpaper_rowGrp_group2 {
	return Wallpaper_rowGrp_group2{
		video2: video2,
		time2:  time2,
	}
}

// Wallpaper_index1 构造 @Type 索引 "index1" 的 map 键（形参与组内字段顺序、类型一致）。
func Wallpaper_index1(video1 string, time1 int) Wallpaper_rowIdx_index1 {
	return Wallpaper_rowIdx_index1{
		video1: video1,
		time1:  time1,
	}
}

type WallpaperTable struct {
	dict           map[int64]*WallpaperRow
	list           []*WallpaperRow
	byGroup_group  map[Wallpaper_rowGrp_group][]*WallpaperRow  // @Type 分组 "group"
	byGroup_group2 map[Wallpaper_rowGrp_group2][]*WallpaperRow // @Type 分组 "group2"
	byIndex_index1 map[Wallpaper_rowIdx_index1]*WallpaperRow   // @Type 索引 "index1"（复合键唯一）
}

func (r *WallpaperTable) load(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &r.list); err != nil {
		return err
	}
	r.dict = make(map[int64]*WallpaperRow)
	for _, row := range r.list {
		r.dict[row.GetID()] = row
	}
	r.byGroup_group = make(map[Wallpaper_rowGrp_group][]*WallpaperRow)
	r.byGroup_group2 = make(map[Wallpaper_rowGrp_group2][]*WallpaperRow)
	r.byIndex_index1 = make(map[Wallpaper_rowIdx_index1]*WallpaperRow)
	for _, row := range r.list {
		kg0 := Wallpaper_group(row.video1, row.time1)
		r.byGroup_group[kg0] = append(r.byGroup_group[kg0], row)
		kg1 := Wallpaper_group2(row.video2, row.time2)
		r.byGroup_group2[kg1] = append(r.byGroup_group2[kg1], row)
		ik0 := Wallpaper_index1(row.video1, row.time1)
		r.byIndex_index1[ik0] = row
	}
	return nil
}

// GetRowsByGroup_group 按 @Type 分组键查询行（形参顺序、类型与 Wallpaper_group 一致）。
func (r *WallpaperTable) GetRowsByGroup_group(video1 string, time1 int) []*WallpaperRow {
	k := Wallpaper_group(video1, time1)
	return r.byGroup_group[k]
}

// GetRowsByGroup_group2 按 @Type 分组键查询行（形参顺序、类型与 Wallpaper_group2 一致）。
func (r *WallpaperTable) GetRowsByGroup_group2(video2 string, time2 int) []*WallpaperRow {
	k := Wallpaper_group2(video2, time2)
	return r.byGroup_group2[k]
}

// GetByIndexKey 按 @Type 索引查询单行（形参顺序、类型与 Wallpaper_index1 一致；复合键表内唯一）。
func (r *WallpaperTable) GetByIndexKey(video1 string, time1 int) *WallpaperRow {
	k := Wallpaper_index1(video1, time1)
	return r.byIndex_index1[k]
}

func (r *WallpaperTable) Get(id int64) *WallpaperRow {
	row, _ := r.dict[id]
	return row
}

func (r *WallpaperTable) Index(idx int) *WallpaperRow {
	if idx < 0 || idx >= len(r.list) {
		return nil
	}
	return r.list[idx]
}

func (r *WallpaperTable) Range(f func(*WallpaperRow) bool) {
	for _, row := range r.dict {
		if !f(row) {
			return
		}
	}
}

func (r *WallpaperTable) SeqRange(f func(*WallpaperRow) bool) {
	for _, row := range r.list {
		if !f(row) {
			return
		}
	}
}

func (r *WallpaperTable) Len() int {
	return len(r.dict)
}
