// Code generated by excel2json from @Type. DO NOT EDIT.

package gamedata

import (
	"ctc/pkg/tablebin"
	"encoding/json"
	"slices"
)

// EmojiRow 对应表 "Emoji" 的一行（JSON 扁平；@Type「分组/索引」用于行视图与 Table 查询）。
type EmojiRow struct {
	id            int64
	name          string
	shortName     string
	icon          string
	unlockType    int
	conditionText string
	speed         []float64
	grids         int
}

type rowJSONAux_Emoji struct {
	ID            int64     `json:"id"`
	Name          string    `json:"Name"`
	ShortName     string    `json:"ShortName"`
	Icon          string    `json:"Icon"`
	UnlockType    int       `json:"UnlockType"`
	ConditionText string    `json:"ConditionText"`
	Speed         []float64 `json:"Speed"`
	Grids         int       `json:"Grids"`
}

func (r *EmojiRow) UnmarshalJSON(data []byte) error {
	var u rowJSONAux_Emoji
	if err := json.Unmarshal(data, &u); err != nil {
		return err
	}
	r.id = u.ID
	r.name = u.Name
	r.shortName = u.ShortName
	r.icon = u.Icon
	r.unlockType = u.UnlockType
	r.conditionText = u.ConditionText
	r.speed = u.Speed
	r.grids = u.Grids
	return nil
}

func (r *EmojiRow) GetID() int64 {
	return r.id
}

func (r *EmojiRow) GetName() string {
	return r.name
}

func (r *EmojiRow) GetShortName() string {
	return r.shortName
}

func (r *EmojiRow) GetIcon() string {
	return r.icon
}

func (r *EmojiRow) GetUnlockType() int {
	return r.unlockType
}

func (r *EmojiRow) GetConditionText() string {
	return r.conditionText
}

func (r *EmojiRow) GetSpeed() []float64 {
	return slices.Clone(r.speed)
}

func (r *EmojiRow) GetGrids() int {
	return r.grids
}

type EmojiTable struct {
	dict map[int64]*EmojiRow
	list []*EmojiRow
}

func (r *EmojiTable) load(path string) error {
	dec, err := tablebin.Open(path)
	if err != nil {
		return err
	}
	n := dec.NumRows()
	r.list = make([]*EmojiRow, 0, n)
	for i := uint64(0); i < n; i++ {
		row := &EmojiRow{}
		row.id, err = dec.ReadInt64Zigzag()
		if err != nil {
			return err
		}
		{
			row.name, err = dec.ReadString()
			if err != nil {
				return err
			}
		}
		{
			row.shortName, err = dec.ReadString()
			if err != nil {
				return err
			}
		}
		{
			row.icon, err = dec.ReadString()
			if err != nil {
				return err
			}
		}
		{
			row.unlockType, err = dec.ReadInt()
			if err != nil {
				return err
			}
		}
		{
			row.conditionText, err = dec.ReadString()
			if err != nil {
				return err
			}
		}
		{
			row.speed, err = dec.ReadFloat64Slice()
			if err != nil {
				return err
			}
		}
		{
			row.grids, err = dec.ReadInt()
			if err != nil {
				return err
			}
		}
		r.list = append(r.list, row)
	}
	r.dict = make(map[int64]*EmojiRow)
	for _, row := range r.list {
		r.dict[row.GetID()] = row
	}
	return nil
}

func (r *EmojiTable) Get(id int64) *EmojiRow {
	row, _ := r.dict[id]
	return row
}

func (r *EmojiTable) Index(idx int) *EmojiRow {
	if idx < 0 || idx >= len(r.list) {
		return nil
	}
	return r.list[idx]
}

func (r *EmojiTable) ForEach(f func(*EmojiRow) bool) {
	for _, row := range r.dict {
		if !f(row) {
			return
		}
	}
}

func (r *EmojiTable) ForEachOrdered(f func(*EmojiRow) bool) {
	for _, row := range r.list {
		if !f(row) {
			return
		}
	}
}

func (r *EmojiTable) Len() int {
	return len(r.dict)
}
