// <auto-generated />
#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GameData;


// 字段名1；字段名2
public readonly record struct TBTestRowGrp_group1(long Field1, string Field2);



// 字段名3；字段名4
public readonly record struct TBTestRowIdx_idx1(double Field3, int Field4);


public partial class TBTestRow
{
	[JsonPropertyName("id")] public long Id { get; set; }
	// 字段名1
	[JsonPropertyName("Field1")] public long Field1 { get; set; } = default!;
	// 字段名2
	[JsonPropertyName("Field2")] public string Field2 { get; set; } = default!;
	// 字段名3
	[JsonPropertyName("Field3")] public double Field3 { get; set; } = default!;
	// 字段名4
	[JsonPropertyName("Field4")] public int Field4 { get; set; } = default!;
	// 字段名5
	[JsonPropertyName("Field5")] public long[] Field5 { get; set; } = default!;
	// 字段名6
	[JsonPropertyName("Field6")] public string[] Field6 { get; set; } = default!;
	// 字段名7
	[JsonPropertyName("Field7")] public double[] Field7 { get; set; } = default!;
	// 字段名8
	[JsonPropertyName("Field8")] public int[] Field8 { get; set; } = default!;
	// 字段名9
	[JsonPropertyName("Field9")] public EnumTest Field9 { get; set; } = default!;
	// 字段名10
	[JsonPropertyName("Field10")] public EnumTest[] Field10 { get; set; } = default!;
	// 字段名11
	[JsonPropertyName("Field11")] public StructTest Field11 { get; set; } = default!;
	// 字段名12
	[JsonPropertyName("Field12")] public StructTest[] Field12 { get; set; } = default!;

	public TBTestRowGrp_group1 ViewAsGroup1() => new TBTestRowGrp_group1(Field1, Field2);

	public TBTestRowIdx_idx1 ViewAsIndex() => new TBTestRowIdx_idx1(Field3, Field4);
}

public partial class TBTestTable
{
	public List<TBTestRow> List { get; private set; } = new();
	public Dictionary<long, TBTestRow> Dict { get; private set; } = new();
	private Dictionary<TBTestRowGrp_group1, List<TBTestRow>> _byGroup_group1 = new();
	private Dictionary<TBTestRowIdx_idx1, TBTestRow> _byIndex_idx1 = new();

	public static TBTestRowGrp_group1 TBTest_group1(long Field1, string Field2) => new TBTestRowGrp_group1(Field1, Field2);

	public static TBTestRowIdx_idx1 TBTest_idx1(double Field3, int Field4) => new TBTestRowIdx_idx1(Field3, Field4);

	public void Load(string path)
	{
		var json = File.ReadAllText(path);
		var rows = JsonSerializer.Deserialize<List<TBTestRow>>(json) ?? new List<TBTestRow>();
		LoadFromRows(rows);
	}

	void LoadFromRows(List<TBTestRow> rows)
	{
		List = rows;
		Dict = new Dictionary<long, TBTestRow>();
		foreach (var row in rows) Dict[row.Id] = row;
		InitGroupAndIndex();
	}

	void InitGroupAndIndex()
	{
		_byGroup_group1.Clear();
		_byIndex_idx1.Clear();
		foreach (var row in List) {
			var kg0 = TBTest_group1(row.Field1, row.Field2);
			if (!_byGroup_group1.TryGetValue(kg0, out var _lg0)) { _lg0 = new List<TBTestRow>(); _byGroup_group1[kg0] = _lg0; }
			_lg0.Add(row);

			var ik0 = TBTest_idx1(row.Field3, row.Field4);
			_byIndex_idx1[ik0] = row;

		}
	}

	public IReadOnlyList<TBTestRow> GetRowsByGroupKey(long Field1, string Field2) {
		var k = TBTest_group1(Field1, Field2);
		return _byGroup_group1.TryGetValue(k, out var v) ? v : System.Array.Empty<TBTestRow>();
	}

	public TBTestRow? GetByIndexKey(double Field3, int Field4) {
		var k = TBTest_idx1(Field3, Field4);
		return _byIndex_idx1.TryGetValue(k, out var v) ? v : null;
	}

	public TBTestRow? Get(long id) => Dict.TryGetValue(id, out var r) ? r : null;

	public TBTestRow? Index(int idx) => (uint)idx < (uint)List.Count ? List[idx] : null;

	public void ForEach(System.Func<TBTestRow, bool> f) {
		foreach (var kv in Dict) { if (!f(kv.Value)) return; }
	}

	public void ForEachOrdered(System.Func<TBTestRow, bool> f) {
		foreach (var row in List) { if (!f(row)) return; }
	}

	public int Len => Dict.Count;
}
