// <auto-generated /> 与 excel2json / pkg/tablebin 一致，勿手改。
#nullable enable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;

namespace GameData;

public sealed class TableBinDecoder
{
    public const int MaxSliceLen = 10_000_000;

    readonly byte[] _buf;
    int _off;
    readonly string[] _strs;

    public ulong NumRows { get; }

    public static TableBinDecoder Open(string path)
    {
        return new TableBinDecoder(File.ReadAllBytes(path));
    }

    public TableBinDecoder(byte[] buf)
    {
        _buf = buf ?? throw new ArgumentNullException(nameof(buf));
        if (_buf.Length < 5)
            throw new InvalidDataException("tablebin: truncated");
        if (_buf[0] != (byte)'T' || _buf[1] != (byte)'B' || _buf[2] != (byte)'B')
            throw new InvalidDataException("tablebin: bad magic");
        if (_buf[3] != 2)
            throw new InvalidDataException("tablebin: unsupported format version");
        _off = 4;
        var nRows = ReadUvarint();
        NumRows = nRows;
        var nStr = ReadUvarint();
        if (nStr > (ulong)MaxSliceLen)
            throw new InvalidDataException("tablebin: corrupt");
        _strs = new string[nStr];
        for (ulong i = 0; i < nStr; i++)
        {
            var l = ReadUvarint();
            if (l > (ulong)MaxSliceLen || _off + (int)l > _buf.Length)
                throw new InvalidDataException("tablebin: corrupt");
            _strs[i] = System.Text.Encoding.UTF8.GetString(_buf, _off, (int)l);
            _off += (int)l;
        }
    }

    ulong ReadUvarint()
    {
        ulong v = 0;
        int shift = 0;
        while (_off < _buf.Length)
        {
            byte c = _buf[_off++];
            v |= (ulong)(c & 0x7f) << shift;
            if (c < 0x80)
                return v;
            shift += 7;
            if (shift > 63)
                throw new InvalidDataException("tablebin: corrupt");
        }
        throw new InvalidDataException("tablebin: truncated");
    }

    long Dezigzag64(ulong u) => (long)(u >> 1) ^ -(long)(u & 1);

    public long ReadInt64Zigzag()
    {
        var u = ReadUvarint();
        return Dezigzag64(u);
    }

    public int ReadInt32Zigzag()
    {
        long z = ReadInt64Zigzag();
        checked
        {
            return (int)z;
        }
    }

    public int ReadInt() => ReadInt32Zigzag();

    public double ReadFloat64()
    {
        if (_off + 8 > _buf.Length)
            throw new InvalidDataException("tablebin: truncated");
        ulong u = BinaryPrimitives.ReadUInt64LittleEndian(_buf.AsSpan(_off));
        _off += 8;
        return BitConverter.Int64BitsToDouble((long)u);
    }

    public string ReadString()
    {
        var idx = ReadUvarint();
        if (idx >= (ulong)_strs.Length)
            throw new InvalidDataException("tablebin: bad string index");
        return _strs[idx];
    }

    public int ReadSliceLen()
    {
        var n = ReadUvarint();
        if (n > (ulong)MaxSliceLen)
            throw new InvalidDataException("tablebin: slice too long");
        return (int)n;
    }

    public int[] ReadIntSlice()
    {
        int n = ReadSliceLen();
        var a = new int[n];
        for (int i = 0; i < n; i++)
            a[i] = ReadInt();
        return a;
    }

    public long[] ReadInt64Slice()
    {
        int n = ReadSliceLen();
        var a = new long[n];
        for (int i = 0; i < n; i++)
            a[i] = ReadInt64Zigzag();
        return a;
    }

    public double[] ReadFloat64Slice()
    {
        int n = ReadSliceLen();
        var a = new double[n];
        for (int i = 0; i < n; i++)
            a[i] = ReadFloat64();
        return a;
    }

    public string[] ReadStringSlice()
    {
        int n = ReadSliceLen();
        var a = new string[n];
        for (int i = 0; i < n; i++)
            a[i] = ReadString();
        return a;
    }

    public int[] ReadInt32ZigzagSliceAsIntArray()
    {
        int n = ReadSliceLen();
        var a = new int[n];
        for (int i = 0; i < n; i++)
            a[i] = ReadInt32Zigzag();
        return a;
    }
}
